<?php

/*
 * This file is part of EC-CUBE
 *
 * Copyright(c) EC-CUBE CO.,LTD. All Rights Reserved.
 *
 * http://www.ec-cube.co.jp/
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Plugin\Maker44\Repository;

use Doctrine\Bundle\DoctrineBundle\Repository\ServiceEntityRepository;
use Doctrine\Persistence\ManagerRegistry;
use Plugin\Maker44\Entity\Maker;

/**
 * Maker.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 *
 * @extends ServiceEntityRepository<Maker>
 */
class MakerRepository extends ServiceEntityRepository
{
    public function __construct(ManagerRegistry $registry, string $entityClass = Maker::class)
    {
        parent::__construct($registry, $entityClass);
    }

    /**
     * Maker create/update
     */
    public function save(Maker $Maker): bool
    {
        $em = $this->getEntityManager();

        if (!$Maker->getId()) {
            $sortNo = $this->createQueryBuilder('m')
                ->select('MAX(m.sort_no)')
                ->getQuery()
                ->getSingleScalarResult();
            if (!$sortNo) {
                $sortNo = 0;
            }
            $Maker->setSortNo($sortNo + 1);

            $em->createQueryBuilder()
                ->update(Maker::class, 'm')
                ->set('m.sort_no', 'm.sort_no + 1')
                ->where('m.sort_no > :sort_no')
                ->setParameter('sort_no', $sortNo)
                ->getQuery()
                ->execute();
        }

        $em->persist($Maker);
        $em->flush();

        return true;
    }

    /**
     * Delete maker.
     */
    public function delete(Maker $Maker): void
    {
        $em = $this->getEntityManager();
        $em->remove($Maker);
        $em->flush();
    }

    /**
     * Move sortNo.
     *
     * @param array<int|string, int> $sortNos
     *
     * @return array<int|string, array<int|string, int>>
     */
    public function moveSortNo(array $sortNos): array
    {
        $results = [];
        foreach ($sortNos as $id => $sortNo) {
            $Maker = $this->find($id);
            if ($Maker->getSortNo() == $sortNo) {
                continue;
            }
            $results[$id] = $sortNos;
            $Maker->setSortNo($sortNo);
            $this->getEntityManager()->persist($Maker);
            $this->getEntityManager()->flush();
        }

        return $results;
    }
}
